CXX=g++
CXXFLAGS=
SRCDIR=${HOME}/source/stong
CXXFLAGS_INC= -I${SRCDIR}

CXXFLAGS_DBG=-Wall ${CXXFLAGS_INC}

GTEST_DIR=${HOME}/local/source/gtest-1.7.0
CXXFLAGS_GTEST=-isystem ${GTEST_DIR}/include -pthread ${GTEST_DIR}/make/gtest_main.a






