CXX=g++
CXXFLAGS=
SRCDIR=${HOME}/source/stong
CXXFLAGS_INC= -I${SRCDIR} -I${HOME}/include/mpack -I${HOME}/include 

CXXFLAGS_DBG=-Wall 

GTEST_DIR=${HOME}/local/source/gtest-1.7.0
CXXFLAGS_GTEST=-isystem ${GTEST_DIR}/include -pthread ${GTEST_DIR}/make/gtest_main.a






