CXX=g++
CXXFLAGS=

SRCDIR=${HOME}/source/stong

CXXFLAGS_DBG=-Wall 

LIBGTEST=-lgtest_main -lgtest -lpthread

RUN_GTEST=${CXX} -o $@ ${CXXFLAGS} ${LIBGTEST}

CXXFLAGS_INC=-I${HOME}/source/projects/csto_ng
#CXXFLAGS_INC= -I${SRCDIR} -I${HOME}/include/mpack -I${HOME}/include
#GTEST_DIR=${HOME}/local/source/gtest-1.7.0
#CXXFLAGS_GTEST=-isystem ${GTEST_DIR}/include -pthread ${GTEST_DIR}/make/gtest_main.a






